// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxg0FlkFe_vbCZjFULn3vZ3HcUGX2q-R0',
    appId: '1:160531026335:web:79c0d8898dd26954eeedaa',
    messagingSenderId: '160531026335',
    projectId: 'corazoncitomexicano-test1',
    authDomain: 'corazoncitomexicano-test1.firebaseapp.com',
    storageBucket: 'corazoncitomexicano-test1.appspot.com',
    measurementId: 'G-Y2FKM8860D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIMgw1MEkRSldQnvk02OKZ35MaSGnmNXM',
    appId: '1:160531026335:android:7899953008d60f34eeedaa',
    messagingSenderId: '160531026335',
    projectId: 'corazoncitomexicano-test1',
    storageBucket: 'corazoncitomexicano-test1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbWzXvxjgIEtWotVMWAzvkOBOCG_E6QCI',
    appId: '1:160531026335:ios:7233edfb53996428eeedaa',
    messagingSenderId: '160531026335',
    projectId: 'corazoncitomexicano-test1',
    storageBucket: 'corazoncitomexicano-test1.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbWzXvxjgIEtWotVMWAzvkOBOCG_E6QCI',
    appId: '1:160531026335:ios:7233edfb53996428eeedaa',
    messagingSenderId: '160531026335',
    projectId: 'corazoncitomexicano-test1',
    storageBucket: 'corazoncitomexicano-test1.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxg0FlkFe_vbCZjFULn3vZ3HcUGX2q-R0',
    appId: '1:160531026335:web:47fd3b7bfe39566beeedaa',
    messagingSenderId: '160531026335',
    projectId: 'corazoncitomexicano-test1',
    authDomain: 'corazoncitomexicano-test1.firebaseapp.com',
    storageBucket: 'corazoncitomexicano-test1.appspot.com',
    measurementId: 'G-J126H1ZK0B',
  );
}
